name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create ZIP
      run: |
        cd backend
        zip -r ../backend.zip .

    - name: Deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: webappproject
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: backend.zip
