name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create ZIP
      run: zip -r frontend.zip .
      working-directory: ./frontend

    - name: Deploy via Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp deployment source config-zip \
            --resource-group webappproject_group \
            --name sbalabmodule3 \
            --src frontend/frontend.zip